name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint and Code Quality
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort mypy

      - name: Run Black (Code Formatting Check)
        run: |
          black --check custom_components/vrr/

      - name: Run isort (Import Sorting Check)
        run: |
          isort --check-only custom_components/vrr/

      - name: Run Flake8 (Linting)
        run: |
          flake8 custom_components/vrr/ --max-line-length=120 --ignore=E501,W503,E203

      - name: Run mypy (Type Checking)
        run: |
          mypy custom_components/vrr/ --ignore-missing-imports
        continue-on-error: true

  hassfest:
    runs-on: ubuntu-latest
    name: Hassfest Validation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Hassfest
        uses: home-assistant/actions/hassfest@master
